development:
  adapter: mysql2
  encoding: utf8
  database: elp_development
  pool: 5
  username: root
  password: MyNewPass
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: elp_test
  pool: 5
  username: root
  password: MyNewPass
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: elp_production
  pool: 5
  username: root
  password: MyNewPass
  socket: /tmp/mysql.sock
